# This rule is not used by the project kontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to webapp.my-apps.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kontroller
    app.kubernetes.io/managed-by: kustomize
  name: myapp-viewer-role
rules:
- apiGroups:
  - webapp.my-apps.com
  resources:
  - myapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my-apps.com
  resources:
  - myapps/status
  verbs:
  - get
