apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kontroller.fullname" . }}-kontroller
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "kontroller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kontroller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kontroller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kontroller.serviceAccountName" . }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}