replicaCount: 2

image:
  repository: tusova194/kontroller
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  serviceAccountName: kontroller-sa


resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Gateway API support
gatewayAPI:
  enabled: true

# Service configuration
service:
  type: ClusterIP
  port: 8080